version: "3.8"

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
      - ./replica-init.js:/docker-entrypoint-initdb.d/replica-init.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    command: mongod --replSet rs0

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    command: mongod --replSet rs0

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    command: mongod --replSet rs0

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
